import { revision } from './records.mjs';
export function previewRepository(store) {
  const initial={students:[{id:'demo-1',name:'Aluno do piloto — exemplo',group:'TCC1',topic:'Comparação de ferramentas de análise de dados',stage:'Metodologia',deadline:'Julho de 2027',status:'Aguardando avaliação',summary:'Exemplo fictício para testar o painel: a revisão foi concluída e o protocolo experimental aguarda sua análise.',activity:'Prévia',gitStatus:'Sem repositório cadastrado'},{id:'demo-2',name:'Aluna do piloto — exemplo',group:'TCC2',topic:'Governança no desenvolvimento de software',stage:'Análise',deadline:'Dezembro de 2026',status:'Atenção',summary:'Exemplo fictício: confirmar evidências da entrega e revisar os critérios de conclusão.',activity:'Prévia',gitStatus:'Sem repositório cadastrado'}],approvals:[{row:2,studentId:'demo-1',student:'Aluno do piloto — exemplo',date:'Prévia',type:'Metodologia',title:'Validar o protocolo experimental.',evidence:'Protocolo de exemplo disponível para sua revisão.',impact:'Alta',status:'Pendente',note:''},{row:3,studentId:'demo-2',student:'Aluna do piloto — exemplo',date:'Prévia',type:'Entrega',title:'Confirmar os critérios da próxima entrega.',evidence:'Exemplo fictício de evidência, sem vínculo com alunos reais.',impact:'Média',status:'Pendente',note:''}],meetings:[{row:2,studentId:'demo-1',student:'Aluno do piloto — exemplo',date:'30/09/2026',noShow:false,tactiq:'Aguardando',actions:'Validar o protocolo experimental',pending:'Ação de exemplo',next:'07/10/2026'}]};
  const data=()=>store.previewGet('dashboard')||structuredClone(initial);
  const versioned=item=>({...item,version:revision(item)});
  return {
    async dashboard(){const d=data();return {...d,approvals:d.approvals.map(versioned),meetings:d.meetings.map(versioned),mode:'preview',loadedAt:new Date().toISOString()};},
    async decide(row,input){const d=data(),a=d.approvals.find(a=>a.row===row);if(!a||revision(a)!==input.version){const e=new Error('O item mudou. Atualize a lista.');e.status=409;throw e;}const before={...a};Object.assign(a,{status:input.status,note:input.note});store.previewSet('dashboard',d);return {before,after:a};},
    async noShow(row,input){const d=data(),m=d.meetings.find(m=>m.row===row);if(!m||revision(m)!==input.version){const e=new Error('O registro mudou. Atualize a lista.');e.status=409;throw e;}const before={...m};m.noShow=input.noShow;store.previewSet('dashboard',d);return {before,after:m};}
  };
}
